Fr63, fixed the tests of fileRoutes
TherapistTrack/TherapistTrack-Backend pull request #16
Opened 2024-08-03 19:20 UTC by xtsebas

2024-08-03 21:59 UTC, DanielRasho requested changes
Por último, agradecería que actualizaras esta rama con los ultimos cambios de la rama `dev`, y agregaras la info de estas nuevas rutas a la documentacion en Redoc (archivos que estan en `/docs`, en el README de `dev` estan las instrucciones de como correr Redoc)

2024-08-03 21:59 UTC, DanielRasho commented on routes/fileRoutes.js
> +router.get('/file/:id', fileController.getFileById)
Las rutas están algo ambiguas, La diferencia entre `/create` y `/upload`, no es aparente, si ambas crean crean un archivo, porque no fusionarlas?

[Este foro habla de como recibir recibir archivos y sus metadatos en una sola request](https://stackoverflow.com/questions/3938569/how-do-i-upload-a-file-with-metadata-using-a-rest-web-service)

Por otro lado las rutas que pidan "id", no lo pidas por parametros de la URL, por temas de seguridad, le facilita el trabajo a hackers a poder hacer CSRF, mejor pidelo en el body de la request.

2024-08-03 21:59 UTC, DanielRasho commented on package.json
> +    "supertest": "^7.0.0",
Remueve supertest de las dependencias del proyecto

2024-08-03 21:59 UTC, DanielRasho commented on controllers/fileController.js
> +exports.createFile = async (req, res) => {
En esta ruta, creo que sería mejor fusionarla con la ruta `/upload`. Aunque eso requerira que ahora la información ya no venga codificada en JSON sino en `multipart/form-data`

2024-08-03 21:59 UTC, DanielRasho commented on controllers/fileController.js
> +      location,
Removería el parametro "location" La localizacion es algo que decidira el backend, y no algo que el cliente deba saber.

2024-08-03 23:50 UTC, DanielRasho requested changes

2024-08-03 23:50 UTC, DanielRasho commented on models/fileModel.js
> +const File = mongoose.model('File', fileSchema)
Comportamiente extraño de crear una colección extra llamada "files"

2024-08-06 21:45 UTC, xtsebas commented on controllers/fileController.js
> +exports.createFile = async (req, res) => {
esta parte no es buena practica, que cada endpoint tenga solo una funcion, no varias

2024-08-09 00:36 UTC, DanielRasho approved these changes

2024-08-09 00:36 UTC, merged