Fr 203
TherapistTrack/TherapistTrack-Backend pull request #43
Opened 2024-10-16 19:04 UTC by xtsebas

refactorizado patientTemplateController con
rollback a base de datos
funciones repetidas en utils
paralelismo de request independientes pero necesarias

2024-10-16 19:42 UTC, Gxrco requested changes

2024-10-16 19:42 UTC, Gxrco commented on controllers/patientTemplateController.js
>      const doctor = await findUserByRoleID(doctorId)
En esta parte del código también se realiza una verificación que se puede agregar al archivo de los checkers.

2024-10-16 19:42 UTC, Gxrco commented on utils/fieldCheckers.js
Aquí podría ir el check de findUserByID que se encuentra en el archivo de utils/checkingTool.js. Eliminarlo después de implementar el cambio.

2024-10-16 21:29 UTC, xtsebas commented
ya nam nam nam

2024-10-17 01:18 UTC, Gxrco commented
Arregle PR rey

2024-10-17 01:29 UTC, xtsebas commented
YA

2024-10-17 01:36 UTC, Gxrco approved these changes

2024-10-17 01:37 UTC, merged